# Site settings
author: Habib Anwar
title: 
header-img: img/home-bg.png
email: habibkhadbai@outlook.com
copyright_name: Habib Anwar
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: HabibKhadbai
github_username:  habibkhadbai

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
